spring.application.name=backend-spring
spring.datasource.url=jdbc:postgresql://localhost:5433/nahnuveem
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect